-- RLS policies generated by gen-rls.ts
-- All tables deny access by default to anon and authenticated roles.
-- Access is only through service_role via the server-side Prisma client.
-- SSOT: reference/05-database/schema.md §RLS

-- The policies below name the Supabase roles `anon` and `authenticated`. On plain Postgres
-- (integration tests, CI) those roles do not exist: create them, without login, if missing.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
    CREATE ROLE anon NOLOGIN;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    CREATE ROLE authenticated NOLOGIN;
  END IF;
END
$$;

ALTER TABLE "Institution" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Person" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Membership" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Guardianship" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Consent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Partner" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Program" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Module" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Subject" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Cohort" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Enrollment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Lesson" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "LessonVersion" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "LessonVersionAsset" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Assessment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AssessmentVersion" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "LessonAssignment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AssessmentAssignment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MediaAsset" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "LessonProgress" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Attempt" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Score" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "LearningEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Accommodation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PaymentPlan" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Installment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Payment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PaymentAgreement" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RestrictionPolicy" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "LiveSession" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Submission" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Certificate" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ImportRun" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AuditLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Notification" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Invitation" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "deny_anon" ON "Institution" FOR ALL TO anon USING (false);
CREATE POLICY "deny_anon" ON "Person" FOR ALL TO anon USING (false);
CREATE POLICY "deny_anon" ON "Membership" FOR ALL TO anon USING (false);
CREATE POLICY "deny_anon" ON "Guardianship" FOR ALL TO anon USING (false);
CREATE POLICY "deny_anon" ON "Consent" FOR ALL TO anon USING (false);
CREATE POLICY "deny_anon" ON "Partner" FOR ALL TO anon USING (false);
CREATE POLICY "deny_anon" ON "Program" FOR ALL TO anon USING (false);
CREATE POLICY "deny_anon" ON "Module" FOR ALL TO anon USING (false);
CREATE POLICY "deny_anon" ON "Subject" FOR ALL TO anon USING (false);
CREATE POLICY "deny_anon" ON "Cohort" FOR ALL TO anon USING (false);
CREATE POLICY "deny_anon" ON "Enrollment" FOR ALL TO anon USING (false);
CREATE POLICY "deny_anon" ON "Lesson" FOR ALL TO anon USING (false);
CREATE POLICY "deny_anon" ON "LessonVersion" FOR ALL TO anon USING (false);
CREATE POLICY "deny_anon" ON "LessonVersionAsset" FOR ALL TO anon USING (false);
CREATE POLICY "deny_anon" ON "Assessment" FOR ALL TO anon USING (false);
CREATE POLICY "deny_anon" ON "AssessmentVersion" FOR ALL TO anon USING (false);
CREATE POLICY "deny_anon" ON "LessonAssignment" FOR ALL TO anon USING (false);
CREATE POLICY "deny_anon" ON "AssessmentAssignment" FOR ALL TO anon USING (false);
CREATE POLICY "deny_anon" ON "MediaAsset" FOR ALL TO anon USING (false);
CREATE POLICY "deny_anon" ON "LessonProgress" FOR ALL TO anon USING (false);
CREATE POLICY "deny_anon" ON "Attempt" FOR ALL TO anon USING (false);
CREATE POLICY "deny_anon" ON "Score" FOR ALL TO anon USING (false);
CREATE POLICY "deny_anon" ON "LearningEvent" FOR ALL TO anon USING (false);
CREATE POLICY "deny_anon" ON "Accommodation" FOR ALL TO anon USING (false);
CREATE POLICY "deny_anon" ON "PaymentPlan" FOR ALL TO anon USING (false);
CREATE POLICY "deny_anon" ON "Installment" FOR ALL TO anon USING (false);
CREATE POLICY "deny_anon" ON "Payment" FOR ALL TO anon USING (false);
CREATE POLICY "deny_anon" ON "PaymentAgreement" FOR ALL TO anon USING (false);
CREATE POLICY "deny_anon" ON "RestrictionPolicy" FOR ALL TO anon USING (false);
CREATE POLICY "deny_anon" ON "LiveSession" FOR ALL TO anon USING (false);
CREATE POLICY "deny_anon" ON "Submission" FOR ALL TO anon USING (false);
CREATE POLICY "deny_anon" ON "Certificate" FOR ALL TO anon USING (false);
CREATE POLICY "deny_anon" ON "ImportRun" FOR ALL TO anon USING (false);
CREATE POLICY "deny_anon" ON "AuditLog" FOR ALL TO anon USING (false);
CREATE POLICY "deny_anon" ON "Notification" FOR ALL TO anon USING (false);
CREATE POLICY "deny_anon" ON "Invitation" FOR ALL TO anon USING (false);

CREATE POLICY "deny_authenticated" ON "Institution" FOR ALL TO authenticated USING (false);
CREATE POLICY "deny_authenticated" ON "Person" FOR ALL TO authenticated USING (false);
CREATE POLICY "deny_authenticated" ON "Membership" FOR ALL TO authenticated USING (false);
CREATE POLICY "deny_authenticated" ON "Guardianship" FOR ALL TO authenticated USING (false);
CREATE POLICY "deny_authenticated" ON "Consent" FOR ALL TO authenticated USING (false);
CREATE POLICY "deny_authenticated" ON "Partner" FOR ALL TO authenticated USING (false);
CREATE POLICY "deny_authenticated" ON "Program" FOR ALL TO authenticated USING (false);
CREATE POLICY "deny_authenticated" ON "Module" FOR ALL TO authenticated USING (false);
CREATE POLICY "deny_authenticated" ON "Subject" FOR ALL TO authenticated USING (false);
CREATE POLICY "deny_authenticated" ON "Cohort" FOR ALL TO authenticated USING (false);
CREATE POLICY "deny_authenticated" ON "Enrollment" FOR ALL TO authenticated USING (false);
CREATE POLICY "deny_authenticated" ON "Lesson" FOR ALL TO authenticated USING (false);
CREATE POLICY "deny_authenticated" ON "LessonVersion" FOR ALL TO authenticated USING (false);
CREATE POLICY "deny_authenticated" ON "LessonVersionAsset" FOR ALL TO authenticated USING (false);
CREATE POLICY "deny_authenticated" ON "Assessment" FOR ALL TO authenticated USING (false);
CREATE POLICY "deny_authenticated" ON "AssessmentVersion" FOR ALL TO authenticated USING (false);
CREATE POLICY "deny_authenticated" ON "LessonAssignment" FOR ALL TO authenticated USING (false);
CREATE POLICY "deny_authenticated" ON "AssessmentAssignment" FOR ALL TO authenticated USING (false);
CREATE POLICY "deny_authenticated" ON "MediaAsset" FOR ALL TO authenticated USING (false);
CREATE POLICY "deny_authenticated" ON "LessonProgress" FOR ALL TO authenticated USING (false);
CREATE POLICY "deny_authenticated" ON "Attempt" FOR ALL TO authenticated USING (false);
CREATE POLICY "deny_authenticated" ON "Score" FOR ALL TO authenticated USING (false);
CREATE POLICY "deny_authenticated" ON "LearningEvent" FOR ALL TO authenticated USING (false);
CREATE POLICY "deny_authenticated" ON "Accommodation" FOR ALL TO authenticated USING (false);
CREATE POLICY "deny_authenticated" ON "PaymentPlan" FOR ALL TO authenticated USING (false);
CREATE POLICY "deny_authenticated" ON "Installment" FOR ALL TO authenticated USING (false);
CREATE POLICY "deny_authenticated" ON "Payment" FOR ALL TO authenticated USING (false);
CREATE POLICY "deny_authenticated" ON "PaymentAgreement" FOR ALL TO authenticated USING (false);
CREATE POLICY "deny_authenticated" ON "RestrictionPolicy" FOR ALL TO authenticated USING (false);
CREATE POLICY "deny_authenticated" ON "LiveSession" FOR ALL TO authenticated USING (false);
CREATE POLICY "deny_authenticated" ON "Submission" FOR ALL TO authenticated USING (false);
CREATE POLICY "deny_authenticated" ON "Certificate" FOR ALL TO authenticated USING (false);
CREATE POLICY "deny_authenticated" ON "ImportRun" FOR ALL TO authenticated USING (false);
CREATE POLICY "deny_authenticated" ON "AuditLog" FOR ALL TO authenticated USING (false);
CREATE POLICY "deny_authenticated" ON "Notification" FOR ALL TO authenticated USING (false);
CREATE POLICY "deny_authenticated" ON "Invitation" FOR ALL TO authenticated USING (false);
