/**
 * Generate RLS policies from Prisma DMMF.
 *
 * Outputs ENABLE ROW LEVEL SECURITY + deny policies for each table.
 * This ensures that anon and authenticated roles cannot access data directly;
 * all access must go through the service_role via the server-side Prisma client.
 *
 * Usage: pnpm --filter @colombia-estudia/scripts db:gen-rls
 */

import { Prisma } from '@prisma/client';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const models = Prisma.dmmf.datamodel.models.map((m) => m.name);

const ROLE_GUARD = `-- The policies below name the Supabase roles \`anon\` and \`authenticated\`. On plain Postgres
-- (integration tests, CI) those roles do not exist: create them, without login, if missing.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
    CREATE ROLE anon NOLOGIN;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    CREATE ROLE authenticated NOLOGIN;
  END IF;
END
$$;`;

const lines: string[] = [
  '-- RLS policies generated by gen-rls.ts',
  '-- All tables deny access by default to anon and authenticated roles.',
  '-- Access is only through service_role via the server-side Prisma client.',
  '-- SSOT: reference/05-database/schema.md §RLS',
  '',
  ...ROLE_GUARD.split('\n'),
  '',
];

// Enable RLS on all tables
for (const model of models) {
  lines.push(`ALTER TABLE "${model}" ENABLE ROW LEVEL SECURITY;`);
}

lines.push('');

// Deny anon for all tables
for (const model of models) {
  lines.push(`CREATE POLICY "deny_anon" ON "${model}" FOR ALL TO anon USING (false);`);
}

lines.push('');

// Deny authenticated for all tables
for (const model of models) {
  lines.push(
    `CREATE POLICY "deny_authenticated" ON "${model}" FOR ALL TO authenticated USING (false);`
  );
}

const output = lines.join('\n') + '\n';
const outputPath = path.join(__dirname, '../../../prisma/sql/002-rls.sql');

fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, output);

console.log(`Generated ${outputPath}`);
console.log(`Models: ${models.length}`);
console.log(`Policies: ${models.length * 2} (deny_anon + deny_authenticated per table)`);
